#!/bin/bash 
set -x
greet(){
read -rp "choice best distro:..........." name


case $name in
	1) echo "kali is the best";;	
	2) echo "ubuntu is widest";;
	3) echo "parrot the assins";;
	*) echo "idk";;
esac
}
while true
do
	greet
	[[ $name == 5 ]] && break	
done
set +x
