#!/bin/bash 

greet() {

name=""
read -p "what is your name: " name 

if [[ "$name" == "farah" ]]
then
	echo "yes the name is $name"
else
	echo "NO"
	echo "try again"
fi 

}

while ! [[ "$name" == "farah" ]]
do
	greet 
	
done

