#!/bin/bash

direc="/home/moha/scripts/"
if [[ -d "$direc" ]]; then
  cd "$direc" || exit 1
  git add .
  git commit -m "aws-practitioner"
  git push -u origin main

else
  echo "file does not exist"
fi
