#!/bin/bash

direc="/home/moha/scripts/"
if [[ -d "$direc" ]]; then
  cd "$direc" || exit 1
  git status --short
  read -p "commit message: " msg
  git add .
  git commit -m "msg"
  git push -u origin main

else
  echo "file does not exist"
fi
