#!/bin/bash 

clear
greet() {
host="192.168.255.255"

if ping -c1 "$host" > /dev/null
then
	echo "is the server is UP attempting to update.."
	sudo dnf update && sudo dnf upgrade -y
else
	echo "NO INTERNET"
fi	
}

echo "WELCOME:.............................................................................................................................."
printf "Do You Wanna Update Your Parrot OS\n"
read user_input

if [[ "$user_input" == "yes" ]]
then
	echo "Updating:.........."
	greet
elif [[ "$user_input" == "no" ]]
then
	echo "You Don't Wanna update"
elif [[ "$user_input" != "yes" ]] && [[ "$user_input" != "no" ]]
then
	echo "INVALID:............"
else
	echo "bye...bye...bye"
fi
