#!/bin/bash 

greet(){
	echo "hello $1"

}

goodbye(){
	echo "bye $1"

}

munira(){


name="farah"

if [[ "$name" == "farah" ]]
then
	echo "hello mr $name:.."
fi 

}

if ! (return 2>/dev/null); then
	# we are being called directly
	greet dave 
	goodbye john
fi

